using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Discord.Net.Scheduler.SourceGenerator;

[Generator(LanguageNames.CSharp)]
public sealed class JobSourceGenerator : IIncrementalGenerator
{
    private const string CronJobAttributeFullName = "Discord.Net.Scheduler.Attributes.CronJobAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var cronJobs = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                CronJobAttributeFullName,
                predicate: static (node, _) => node is ClassDeclarationSyntax,
                transform: static (ctx, _) => GetJobInfo(ctx))
            .Where(static info => info is not null)
            .Collect();

        context.RegisterSourceOutput(
            cronJobs,
            static (spc, jobs) => GenerateCronJobRegistrations(spc, jobs!));
    }

    private static JobInfo? GetJobInfo(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetNode is not ClassDeclarationSyntax classDecl)
            return null;

        var semanticModel = context.SemanticModel;
        var classSymbol = semanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;

        if (classSymbol is null)
            return null;

        var ns = classSymbol.ContainingNamespace?.ToDisplayString() ?? "";
        var className = classSymbol.Name;
        var fullTypeName = classSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        var attributeData = context.Attributes[0];
        var cronExpression = attributeData.ConstructorArguments.FirstOrDefault().Value as string ?? "";

        var timezone = "";
        var maxRetries = 3;
        var retryDelay = 30;

        foreach (var namedArg in attributeData.NamedArguments)
        {
            switch (namedArg.Key)
            {
                case "Timezone":
                    timezone = namedArg.Value.Value as string ?? "";
                    break;
                case "MaxRetries":
                    maxRetries = (int)(namedArg.Value.Value ?? 3);
                    break;
                case "RetryDelaySeconds":
                    retryDelay = (int)(namedArg.Value.Value ?? 30);
                    break;
            }
        }

        return new JobInfo(ns, className, fullTypeName, cronExpression, timezone, maxRetries, retryDelay);
    }

    private static void GenerateCronJobRegistrations(
        SourceProductionContext context,
        ImmutableArray<JobInfo> jobs)
    {
        if (jobs.IsEmpty)
            return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#pragma warning disable CS8600, CS8602, CS8603, CS8604, CS8618");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        sb.AppendLine("using Discord.Net.Scheduler.Scheduling;");
        sb.AppendLine();
        sb.AppendLine("namespace Discord.Net.Scheduler.SourceGenerated");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class CronJobRegistrar");
        sb.AppendLine("    {");
        sb.AppendLine("        public static IServiceCollection AddGeneratedCronJobs(this IServiceCollection services)");
        sb.AppendLine("        {");

        foreach (var job in jobs)
        {
            sb.AppendLine($"            services.TryAddTransient<{job.FullTypeName}>();");
            sb.AppendLine($"            services.AddSingleton<ICronJobRegistration>(sp =>");
            sb.AppendLine($"                new CronJobRegistration_(\"{job.ClassName}\", \"{job.CronExpression}\", sp));");
        }

        sb.AppendLine("            return services;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("CronJobRegistrar.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private sealed class JobInfo
    {
        public string Namespace { get; }
        public string ClassName { get; }
        public string FullTypeName { get; }
        public string CronExpression { get; }
        public string Timezone { get; }
        public int MaxRetries { get; }
        public int RetryDelay { get; }

        public JobInfo(
            string ns,
            string className,
            string fullTypeName,
            string cronExpression,
            string timezone,
            int maxRetries,
            int retryDelay)
        {
            Namespace = ns;
            ClassName = className;
            FullTypeName = fullTypeName;
            CronExpression = cronExpression;
            Timezone = timezone;
            MaxRetries = maxRetries;
            RetryDelay = retryDelay;
        }
    }
}
